# Generated by Django 5.1 on 2025-12-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
