# Generated by Django 5.1 on 2025-12-20 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmbodiedCarbon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.CharField(max_length=100)),
                ("weight_kg", models.FloatField()),
                ("location_of_factory", models.CharField(max_length=100)),
                ("lifetime_years", models.FloatField()),
                ("location_of_use", models.CharField(max_length=100)),
                ("electricity_usage_kwh", models.FloatField(blank=True, null=True)),
                ("capacity_kw", models.FloatField(blank=True, null=True)),
                (
                    "refrigerant_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("refrigerant_charge_kg", models.FloatField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embodied_carbons",
                        to="embodiedcarbonapp.project",
                    ),
                ),
            ],
        ),
    ]
