# Generated by Django 5.1 on 2025-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbodiedCarbon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("product_type", models.CharField(max_length=100)),
                ("weight_kg", models.FloatField()),
                ("location_of_factory", models.CharField(max_length=100)),
                ("lifetime_years", models.FloatField()),
                ("location_of_use", models.CharField(max_length=100)),
                ("electricity_usage_kwh", models.FloatField(blank=True, null=True)),
                ("capacity_kw", models.FloatField(blank=True, null=True)),
                (
                    "refrigerant_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("refrigerant_charge_kg", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
