# Generated by Django 5.1 on 2025-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbodiedCarbon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.CharField(max_length=100)),
                ("material", models.CharField(max_length=100)),
                ("weight_kg", models.FloatField()),
                ("total_a1_embodied_carbon", models.FloatField(default=0)),
            ],
        ),
    ]
