# Generated by Django 5.1 on 2025-11-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embodiedcarbon",
            name="total_a1_embodied_carbon",
        ),
    ]
