# Generated by Django 5.1 on 2025-11-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0002_remove_embodiedcarbon_total_a1_embodied_carbon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embodiedcarbon",
            name="material",
        ),
    ]
