# Generated by Django 5.1 on 2025-11-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0003_remove_embodiedcarbon_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="embodiedcarbon",
            name="electricity_usage_kwh",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
