# Generated by Django 5.1 on 2025-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0004_embodiedcarbon_electricity_usage_kwh"),
    ]

    operations = [
        migrations.AddField(
            model_name="embodiedcarbon",
            name="location_of_factory",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
