# Generated by Django 5.1 on 2025-12-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0005_embodiedcarbon_location_of_factory"),
    ]

    operations = [
        migrations.AddField(
            model_name="embodiedcarbon",
            name="lifetime_years",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="embodiedcarbon",
            name="location_of_use",
            field=models.CharField(
                choices=[
                    ("australia_within_state_manufactured", "Australia within state "),
                    ("australia_nationally_manufactured", "Australia interstate"),
                    (
                        "new_zealand_within_region_manufactured",
                        "New Zealand within region",
                    ),
                    ("new_zealand_nationally_manufactured", "New Zealand interregion"),
                    (
                        "australia_nz_globally_manufactured_asia",
                        "Australia/NZ globally manufactured - Asia",
                    ),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="embodiedcarbon",
            name="refrigerant_charge_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="embodiedcarbon",
            name="refrigerant_leakage_rate_pct_per_year",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="embodiedcarbon",
            name="refrigerant_used",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
