# Generated by Django 5.1 on 2025-12-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0006_embodiedcarbon_lifetime_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embodiedcarbon",
            name="location_of_use",
            field=models.CharField(
                choices=[
                    (
                        "australia_within_state_manufactured",
                        "australia_within_state_manufactured",
                    ),
                    (
                        "australia_nationally_manufactured",
                        "australia_nationally_manufactured",
                    ),
                    (
                        "new_zealand_within_region_manufactured",
                        "new_zealand_within_region_manufactured",
                    ),
                    (
                        "new_zealand_nationally_manufactured",
                        "new_zealand_nationally_manufactured",
                    ),
                    (
                        "australia_nz_globally_manufactured_asia",
                        "australia_nz_globally_manufactured_asia",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
