# Generated by Django 5.1 on 2025-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0007_alter_embodiedcarbon_location_of_use"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embodiedcarbon",
            name="refrigerant_leakage_rate_pct_per_year",
        ),
        migrations.AlterField(
            model_name="embodiedcarbon",
            name="refrigerant_used",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R-410A", "R-410A"),
                    ("R-32", "R-32"),
                    ("R-134a", "R-134a"),
                    ("R-407C", "R-407C"),
                    ("R-290", "R-290"),
                    ("R11", "R11"),
                    ("R22", "R22"),
                    ("R600a", "R600a"),
                    ("R744", "R744"),
                    ("R717", "R717"),
                    ("R718", "R718"),
                    ("R1234yf", "R1234yf"),
                    ("R1234ze", "R1234ze"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
