# Generated by Django 5.1 on 2025-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "embodiedcarbonapp",
            "0008_remove_embodiedcarbon_refrigerant_leakage_rate_pct_per_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="embodiedcarbon",
            name="capacity_kw",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
