# Generated by Django 5.1 on 2025-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0009_embodiedcarbon_capacity_kw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embodiedcarbon",
            name="location_of_use",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="embodiedcarbon",
            name="refrigerant_used",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
