# Generated by Django 5.1 on 2025-12-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0010_alter_embodiedcarbon_location_of_use_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embodiedcarbon",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="embodiedcarbon",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
