# Generated by Django 5.1 on 2025-12-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0011_embodiedcarbon_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embodiedcarbon",
            name="date_modified",
        ),
    ]
