# Generated by Django 5.1 on 2025-12-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0012_remove_embodiedcarbon_date_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embodiedcarbon",
            name="date_created",
        ),
    ]
