# Generated by Django 5.1 on 2025-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embodiedcarbonapp", "0013_remove_embodiedcarbon_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="embodiedcarbon",
            name="project_name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
